id:485,en:"much",tr:"çok (sayılamaz)",level:"A1"},
    {id:486,en:"more",tr:"daha fazla",level:"A1"},
    {id:487,en:"most",tr:"en çok",level:"A1"},
    {id:488,en:"less",tr:"daha az",level:"A1"},
    {id:489,en:"few",tr:"az",level:"A1"},
    {id:490,en:"little",tr:"küçük/az",level:"A1"},
    {id:491,en:"other",tr:"diğer",level:"A1"},
    {id:492,en:"another",tr:"başka bir",level:"A1"},
    {id:493,en:"every",tr:"her",level:"A1"},
    {id:494,en:"each",tr:"her bir",level:"A1"},
    {id:495,en:"both",tr:"ikisi de",level:"A1"},
    {id:496,en:"everything",tr:"her şey",level:"A1"},
    {id:497,en:"everyone",tr:"herkes",level:"A1"},
    {id:498,en:"something",tr:"bir şey",level:"A1"},
    {id:499,en:"someone",tr:"biri",level:"A1"},
    {id:500,en:"nothing",tr:"hiçbir şey",level:"A1"},
    
    // Daha fazla A1 kelime
    {id:501,en:"yes",tr:"evet",level:"A1"},
    {id:502,en:"no",tr:"hayır",level:"A1"},
    {id:503,en:"please",tr:"lütfen",level:"A1"},
    {id:504,en:"thank",tr:"teşekkür etmek",level:"A1"},
    {id:505,en:"sorry",tr:"özür",level:"A1"},
    {id:506,en:"hello",tr:"merhaba",level:"A1"},
    {id:507,en:"goodbye",tr:"hoşça kal",level:"A1"},
    {id:508,en:"welcome",tr:"hoş geldin",level:"A1"},
    {id:509,en:"excuse",tr:"affetmek",level:"A1"},
    {id:510,en:"understand",tr:"anlamak",level:"A1"},
    {id:511,en:"remember",tr:"hatırlamak",level:"A1"},
    {id:512,en:"forget",tr:"unutmak",level:"A1"},
    {id:513,en:"believe",tr:"inanmak",level:"A1"},
    {id:514,en:"agree",tr:"katılmak",level:"A1"},
    {id:515,en:"decide",tr:"karar vermek",level:"A1"},
    {id:516,en:"choose",tr:"seçmek",level:"A1"},
    {id:517,en:"prefer",tr:"tercih etmek",level:"A1"},
    {id:518,en:"enjoy",tr:"keyif almak",level:"A1"},
    {id:519,en:"hate",tr:"nefret etmek",level:"A1"},
    {id:520,en:"miss",tr:"özlemek",level:"A1"},
    {id:521,en:"travel",tr:"seyahat etmek",level:"A1"},
    {id:522,en:"visit",tr:"ziyaret etmek",level:"A1"},
    {id:523,en:"arrive",tr:"varmak",level:"A1"},
    {id:524,en:"return",tr:"dönmek",level:"A1"},
    {id:525,en:"bring",tr:"getirmek",level:"A1"},
    {id:526,en:"carry",tr:"taşımak",level:"A1"},
    {id:527,en:"send",tr:"göndermek",level:"A1"},
    {id:528,en:"receive",tr:"almak",level:"A1"},
    {id:529,en:"share",tr:"paylaşmak",level:"A1"},
    {id:530,en:"save",tr:"kurtarmak/biriktirmek",level:"A1"},
    {id:531,en:"spend",tr:"harcamak",level:"A1"},
    {id:532,en:"keep",tr:"tutmak",level:"A1"},
    {id:533,en:"lose",tr:"kaybetmek",level:"A1"},
    {id:534,en:"win",tr:"kazanmak",level:"A1"},
    {id:535,en:"catch",tr:"yakalamak",level:"A1"},
    {id:536,en:"throw",tr:"fırlatmak",level:"A1"},
    {id:537,en:"pull",tr:"çekmek",level:"A1"},
    {id:538,en:"push",tr:"itmek",level:"A1"},
    {id:539,en:"hold",tr:"tutmak",level:"A1"},
    {id:540,en:"touch",tr:"dokunmak",level:"A1"},
    {id:541,en:"break",tr:"kırmak",level:"A1"},
    {id:542,en:"fix",tr:"tamir etmek",level:"A1"},
    {id:543,en:"build",tr:"inşa etmek",level:"A1"},
    {id:544,en:"cut",tr:"kesmek",level:"A1"},
    {id:545,en:"draw",tr:"çizmek",level:"A1"},
    {id:546,en:"paint",tr:"boyamak",level:"A1"},
    {id:547,en:"cook",tr:"pişirmek",level:"A1"},
    {id:548,en:"wash",tr:"yıkamak",level:"A1"},
    {id:549,en:"clean",tr:"temizlemek",level:"A1"},
    {id:550,en:"dress",tr:"giyinmek",level:"A1"},
    
    // ==================== A2 SEVİYESİ (310 kelime) ====================
    {id:551,en:"accept",tr:"kabul etmek",level:"A2"},
    {id:552,en:"achieve",tr:"başarmak",level:"A2"},
    {id:553,en:"add",tr:"eklemek",level:"A2"},
    {id:554,en:"admire",tr:"hayran olmak",level:"A2"},
    {id:555,en:"admit",tr:"itiraf etmek",level:"A2"},
    {id:556,en:"adopt",tr:"evlat edinmek",level:"A2"},
    {id:557,en:"advertise",tr:"reklam yapmak",level:"A2"},
    {id:558,en:"affect",tr:"etkilemek",level:"A2"},
    {id:559,en:"afford",tr:"gücü yetmek",level:"A2"},
    {id:560,en:"aim",tr:"hedeflemek",level:"A2"},
    {id:561,en:"allow",tr:"izin vermek",level:"A2"},
    {id:562,en:"announce",tr:"duyurmak",level:"A2"},
    {id:563,en:"apologize",tr:"özür dilemek",level:"A2"},
    {id:564,en:"appear",tr:"görünmek",level:"A2"},
    {id:565,en:"apply",tr:"başvurmak",level:"A2"},
    {id:566,en:"appreciate",tr:"takdir etmek",level:"A2"},
    {id:567,en:"approach",tr:"yaklaşmak",level:"A2"},
    {id:568,en:"approve",tr:"onaylamak",level:"A2"},
    {id:569,en:"argue",tr:"tartışmak",level:"A2"},
    {id:570,en:"arrange",tr:"düzenlemek",level:"A2"},
    {id:571,en:"arrest",tr:"tutuklamak",level:"A2"},
    {id:572,en:"assume",tr:"varsaymak",level:"A2"},
    {id:573,en:"attach",tr:"eklemek",level:"A2"},
    {id:574,en:"attack",tr:"saldırmak",level:"A2"},
    {id:575,en:"attempt",tr:"teşebbüs etmek",level:"A2"},
    {id:576,en:"attend",tr:"katılmak",level:"A2"},
    {id:577,en:"attract",tr:"çekmek",level:"A2"},
    {id:578,en:"avoid",tr:"kaçınmak",level:"A2"},
    {id:579,en:"aware",tr:"farkında",level:"A2"},
    {id:580,en:"balance",tr:"denge",level:"A2"},
    {id:581,en:"ban",tr:"yasaklamak",level:"A2"},
    {id:582,en:"base",tr:"temel",level:"A2"},
    {id:583,en:"beat",tr:"yenmek",level:"A2"},
    {id:584,en:"behave",tr:"davranmak",level:"A2"},
    {id:585,en:"belong",tr:"ait olmak",level:"A2"},
    {id:586,en:"benefit",tr:"fayda",level:"A2"},
    {id:587,en:"blame",tr:"suçlamak",level:"A2"},
    {id:588,en:"borrow",tr:"ödünç almak",level:"A2"},
    {id:589,en:"bother",tr:"rahatsız etmek",level:"A2"},
    {id:590,en:"breathe",tr:"nefes almak",level:"A2"},
    {id:591,en:"burn",tr:"yakmak",level:"A2"},
    {id:592,en:"bury",tr:"gömmek",level:"A2"},
    {id:593,en:"calculate",tr:"hesaplamak",level:"A2"},
    {id:594,en:"cancel",tr:"iptal etmek",level:"A2"},
    {id:595,en:"celebrate",tr:"kutlamak",level:"A2"},
    {id:596,en:"challenge",tr:"meydan okumak",level:"A2"},
    {id:597,en:"chance",tr:"şans",level:"A2"},
    {id:598,en:"charge",tr:"şarj etmek",level:"A2"},
    {id:599,en:"chase",tr:"kovalamak",level:"A2"},
    {id:600,en:"cheat",tr:"hile yapmak",level:"A2"},
    {id:601,en:"check",tr:"kontrol etmek",level:"A2"},
    {id:602,en:"claim",tr:"iddia etmek",level:"A2"},
    {id:603,en:"climb",tr:"tırmanmak",level:"A2"},
    {id:604,en:"collect",tr:"toplamak",level:"A2"},
    {id:605,en:"combine",tr:"birleştirmek",level:"A2"},
    {id:606,en:"comfort",tr:"rahatlık",level:"A2"},
    {id:607,en:"command",tr:"komut",level:"A2"},
    {id:608,en:"comment",tr:"yorum",level:"A2"},
    {id:609,en:"communicate",tr:"iletişim kurmak",level:"A2"},
    {id:610,en:"compare",tr:"karşılaştırmak",level:"A2"},
    {id:611,en:"compete",tr:"yarışmak",level:"A2"},
    {id:612,en:"complain",tr:"şikayet etmek",level:"A2"},
    {id:613,en:"complete",tr:"tamamlamak",level:"A2"},
    {id:614,en:"concentrate",tr:"konsantre olmak",level:"A2"},
    {id:615,en:"concern",tr:"endişe",level:"A2"},
    {id:616,en:"conclusion",tr:"sonuç",level:"A2"},
    {id:617,en:"condition",tr:"durum",level:"A2"},
    {id:618,en:"confirm",tr:"onaylamak",level:"A2"},
    {id:619,en:"confuse",tr:"karıştırmak",level:"A2"},
    {id:620,en:"connect",tr:"bağlamak",level:"A2"},
    {id:621,en:"consider",tr:"düşünmek",level:"A2"},
    {id:622,en:"consist",tr:"oluşmak",level:"A2"},
    {id:623,en:"contact",tr:"iletişim",level:"A2"},
    {id:624,en:"contain",tr:"içermek",level:"A2"},
    {id:625,en:"continue",tr:"devam etmek",level:"A2"},
    {id:626,en:"contribute",tr:"katkıda bulunmak",level:"A2"},
    {id:627,en:"control",tr:"kontrol",level:"A2"},
    {id:628,en:"conversation",tr:"konuşma",level:"A2"},
    {id:629,en:"convince",tr:"ikna etmek",level:"A2"},
    {id:630,en:"copy",tr:"kopya",level:"A2"},
    {id:631,en:"correct",tr:"doğru",level:"A2"},
    {id:632,en:"cost",tr:"maliyet",level:"A2"},
    {id:633,en:"count",tr:"saymak",level:"A2"},
    {id:634,en:"courage",tr:"cesaret",level:"A2"},
    {id:635,en:"cover",tr:"kapak",level:"A2"},
    {id:636,en:"crash",tr:"çarpışmak",level:"A2"},
    {id:637,en:"create",tr:"yaratmak",level:"A2"},
    {id:638,en:"cross",tr:"geçmek",level:"A2"},
    {id:639,en:"crowd",tr:"kalabalık",level:"A2"},
    {id:640,en:"culture",tr:"kültür",level:"A2"},
    {id:641,en:"customer",tr:"müşteri",level:"A2"},
    {id:642,en:"damage",tr:"hasar",level:"A2"},
    {id:643,en:"danger",tr:"tehlike",level:"A2"},
    {id:644,en:"data",tr:"veri",level:"A2"},
    {id:645,en:"deal",tr:"anlaşma",level:"A2"},
    {id:646,en:"debate",tr:"tartışma",level:"A2"},
    {id:647,en:"debt",tr:"borç",level:"A2"},
    {id:648,en:"decline",tr:"düşüş",level:"A2"},
    {id:649,en:"decorate",tr:"süslemek",level:"A2"},
    {id:650,en:"decrease",tr:"azalmak",level:"A2"},
    
    // ==================== B1 SEVİYESİ (556 kelime) ====================
    {id:651,en:"abandon",tr:"terk etmek",level:"B1"},
    {id:652,en:"absence",tr:"yokluk",level:"B1"},
    {id:653,en:"absolute",tr:"mutlak",level:"B1"},
    {id:654,en:"absorb",tr:"emmek",level:"B1"},
    {id:655,en:"abstract",tr:"soyut",level:"B1"},
    {id:656,en:"abuse",tr:"istismar",level:"B1"},
    {id:657,en:"academic",tr:"akademik",level:"B1"},
    {id:658,en:"access",tr:"erişim",level:"B1"},
    {id:659,en:"accident",tr:"kaza",level:"B1"},
    {id:660,en:"accommodate",tr:"barındırmak",level:"B1"},
    {id:661,en:"accompany",tr:"eşlik etmek",level:"B1"},
    {id:662,en:"accomplish",tr:"başarmak",level:"B1"},
    {id:663,en:"account",tr:"hesap",level:"B1"},
    {id:664,en:"accurate",tr:"doğru",level:"B1"},
    {id:665,en:"accuse",tr:"suçlamak",level:"B1"},
    {id:666,en:"acknowledge",tr:"kabul etmek",level:"B1"},
    {id:667,en:"acquire",tr:"edinmek",level:"B1"},
    {id:668,en:"actual",tr:"gerçek",level:"B1"},
    {id:669,en:"adapt",tr:"uyum sağlamak",level:"B1"},
    {id:670,en:"addition",tr:"ek",level:"B1"},
    {id:671,en:"address",tr:"adres",level:"B1"},
    {id:672,en:"adequate",tr:"yeterli",level:"B1"},
    {id:673,en:"adjust",tr:"ayarlamak",level:"B1"},
    {id:674,en:"administration",tr:"yönetim",level:"B1"},
    {id:675,en:"advance",tr:"ilerleme",level:"B1"},
    {id:676,en:"advantage",tr:"avantaj",level:"B1"},
    {id:677,en:"adventure",tr:"macera",level:"B1"},
    {id:678,en:"advertisement",tr:"reklam",level:"B1"},
    {id:679,en:"advice",tr:"tavsiye",level:"B1"},
    {id:680,en:"affair",tr:"mesele",level:"B1"},
    {id:681,en:"agency",tr:"ajans",level:"B1"},
    {id:682,en:"agent",tr:"ajan",level:"B1"},
    {id:683,en:"aggressive",tr:"agresif",level:"B1"},
    {id:684,en:"agriculture",tr:"tarım",level:"B1"},
    {id:685,en:"aid",tr:"yardım",level:"B1"},
    {id:686,en:"aircraft",tr:"uçak",level:"B1"},
    {id:687,en:"alarm",tr:"alarm",level:"B1"},
    {id:688,en:"alcohol",tr:"alkol",level:"B1"},
    {id:689,en:"alive",tr:"canlı",level:"B1"},
    {id:690,en:"alliance",tr:"ittifak",level:"B1"},
    {id:691,en:"alternative",tr:"alternatif",level:"B1"},
    {id:692,en:"altogether",tr:"tamamen",level:"B1"},
    {id:693,en:"amazing",tr:"şaşırtıcı",level:"B1"},
    {id:694,en:"ambitious",tr:"hırslı",level:"B1"},
    {id:695,en:"amount",tr:"miktar",level:"B1"},
    {id:696,en:"analyse",tr:"analiz etmek",level:"B1"},
    {id:697,en:"ancient",tr:"antik",level:"B1"},
    {id:698,en:"angle",tr:"açı",level:"B1"},
    {id:699,en:"annual",tr:"yıllık",level:"B1"},
    {id:700,en:"anxious",tr:"endişeli",level:"B1"},
    
    // ==================== B2 SEVİYESİ (1280 kelime) ====================
    {id:701,en:"abolish",tr:"kaldırmak",level:"B2"},
    {id:702,en:"abortion",tr:"kürtaj",level:"B2"},
    {id:703,en:"abrupt",tr:"ani",level:"B2"},
    {id:704,en:"abundance",tr:"bolluk",level:"B2"},
    {id:705,en:"accelerate",tr:"hızlandırmak",level:"B2"},
    {id:706,en:"acceptable",tr:"kabul edilebilir",level:"B2"},
    {id:707,en:"accessible",tr:"erişilebilir",level:"B2"},
    {id:708,en:"acclaim",tr:"alkışlamak",level:"B2"},
    {id:709,en:"accommodation",tr:"konaklama",level:"B2"},
    {id:710,en:"accountability",tr:"hesap verebilirlik",level:"B2"},
    {id:711,en:"accumulate",tr:"biriktirmek",level:"B2"},
    {id:712,en:"accuracy",tr:"doğruluk",level:"B2"},
    {id:713,en:"accusation",tr:"suçlama",level:"B2"},
    {id:714,en:"achievement",tr:"başarı",level:"B2"},
    {id:715,en:"acid",tr:"asit",level:"B2"},
    {id:716,en:"acknowledgement",tr:"kabul",level:"B2"},
    {id:717,en:"acquisition",tr:"edinim",level:"B2"},
    {id:718,en:"activate",tr:"etkinleştirmek",level:"B2"},
    {id:719,en:"acute",tr:"akut",level:"B2"},
    {id:720,en:"addiction",tr:"bağımlılık",level:"B2"},
    {id:721,en:"administrator",tr:"yönetici",level:"B2"},
    {id:722,en:"adolescent",tr:"ergen",level:"B2"},
    {id:723,en:"adverse",tr:"olumsuz",level:"B2"},
    {id:724,en:"advocate",tr:"savunucu",level:"B2"},
    {id:725,en:"aesthetic",tr:"estetik",level:"B2"},
    {id:726,en:"affection",tr:"sevgi",level:"B2"},
    {id:727,en:"affordable",tr:"uygun fiyatlı",level:"B2"},
    {id:728,en:"agenda",tr:"gündem",level:"B2"},
    {id:729,en:"aggregate",tr:"toplam",level:"B2"},
    {id:730,en:"aggression",tr:"saldırganlık",level:"B2"},
    {id:731,en:"align",tr:"hizalamak",level:"B2"},
    {id:732,en:"allegation",tr:"iddia",level:"B2"},
    {id:733,en:"allocate",tr:"tahsis etmek",level:"B2"},
    {id:734,en:"alter",tr:"değiştirmek",level:"B2"},
    {id:735,en:"ambiguous",tr:"belirsiz",level:"B2"},
    {id:736,en:"amendment",tr:"değişiklik",level:"B2"},
    {id:737,en:"amid",tr:"arasında",level:"B2"},
    {id:738,en:"analogy",tr:"benzetme",level:"B2"},
    {id:739,en:"analyst",tr:"analist",level:"B2"},
    {id:740,en:"ancestor",tr:"ata",level:"B2"},
    {id:741,en:"anchor",tr:"çapa",level:"B2"},
    {id:742,en:"animation",tr:"animasyon",level:"B2"},
    {id:743,en:"anonymous",tr:"anonim",level:"B2"},
    {id:744,en:"anticipate",tr:"öngörmek",level:"B2"},
    {id:745,en:"anxiety",tr:"kaygı",level:"B2"},
    {id:746,en:"apparatus",tr:"cihaz",level:"B2"},
    {id:747,en:"appeal",tr:"itiraz",level:"B2"},
    {id:748,en:"appliance",tr:"cihaz",level:"B2"},
    {id:749,en:"applicable",tr:"uygulanabilir",level:"B2"},
    {id:750,en:"applicant",tr:"başvuru sahibi",level:"B2"},
    
    // ==================== C1 SEVİYESİ (1251 kelime) ====================
    {id:751,en:"aberration",tr:"sapma",level:"C1"},
    {id:752,en:"abide",tr:"uymak",level:"C1"},
    {id:753,en:"abnormal",tr:"anormal",level:"C1"},
    {id:754,en:"abolition",tr:"kaldırma",level:"C1"},
    {id:755,en:"abound",tr:"bol olmak",level:"C1"},
    {id:756,en:"abrasive",tr:"aşındırıcı",level:"C1"},
    {id:757,en:"abreast",tr:"yan yana",level:"C1"},
    {id:758,en:"abstain",tr:"kaçınmak",level:"C1"},
    {id:759,en:"abstraction",tr:"soyutlama",level:"C1"},
    {id:760,en:"absurd",tr:"saçma",level:"C1"},
    {id:761,en:"accelerator",tr:"hızlandırıcı",level:"C1"},
    {id:762,en:"accentuate",tr:"vurgulamak",level:"C1"},
    {id:763,en:"accomplishment",tr:"başarı",level:"C1"},
    {id:764,en:"accord",tr:"anlaşma",level:"C1"},
    {id:765,en:"accountability",tr:"sorumluluk",level:"C1"},
    {id:766,en:"accredited",tr:"akredite",level:"C1"},
    {id:767,en:"acumen",tr:"zeka",level:"C1"},
    {id:768,en:"adamant",tr:"kararlı",level:"C1"},
    {id:769,en:"addendum",tr:"ek",level:"C1"},
    {id:770,en:"adept",tr:"usta",level:"C1"},
    {id:771,en:"adherent",tr:"taraftar",level:"C1"},
    {id:772,en:"adjourn",tr:"ertelemek",level:"C1"},
    {id:773,en:"adjunct",tr:"yardımcı",level:"C1"},
    {id:774,en:"administer",tr:"yönetmek",level:"C1"},
    {id:775,en:"admirable",tr:"takdire değer",level:"C1"},
    {id:776,en:"adorn",tr:"süslemek",level:"C1"},
    {id:777,en:"advent",tr:"gelişi",level:"C1"},
    {id:778,en:"adversary",tr:"hasım",level:"C1"},
    {id:779,en:"adversity",tr:"zorluk",level:"C1"},
    {id:780,en:"advocacy",tr:"savunuculuk",level:"C1"},
    {id:781,en:"affiliate",tr:"bağlı kuruluş",level:"C1"},
    {id:782,en:"affirmative",tr:"olumlu",level:"C1"},
    {id:783,en:"afflict",tr:"eziyet etmek",level:"C1"},
    {id:784,en:"affluent",tr:"zengin",level:"C1"},
    {id:785,en:"aftermath",tr:"sonuç",level:"C1"},
    {id:786,en:"aggravate",tr:"kötüleştirmek",level:"C1"},
    {id:787,en:"ailment",tr:"rahatsızlık",level:"C1"},
    {id:788,en:"albeit",tr:"her ne kadar",level:"C1"},
    {id:789,en:"alchemy",tr:"simya",level:"C1"},
    {id:790,en:"algorithm",tr:"algoritma",level:"C1"},
    {id:791,en:"alienate",tr:"yabancılaştırmak",level:"C1"},
    {id:792,en:"alignment",tr:"hizalama",level:"C1"},
    {id:793,en:"allegiance",tr:"bağlılık",level:"C1"},
    {id:794,en:"alleviate",tr:"hafifletmek",level:"C1"},
    {id:795,en:"allot",tr:"pay vermek",level:"C1"},
    {id:796,en:"allure",tr:"çekicilik",level:"C1"},
    {id:797,en:"ally",tr:"müttefik",level:"C1"},
    {id:798,en:"alteration",tr:"değişiklik",level:"C1"},
    {id:799,en:"altitude",tr:"yükseklik",level:"C1"},
    {id:800,en:"altruism",tr:"özgecilik",level:"C1"}
];

// Ek A1 kelimeleri (toplam 1479'a tamamlamak için)
const additionalA1 = [
    {id:801,en:"air",tr:"hava",level:"A1"},
    {id:802,en:"area",tr:"alan",level:"A1"},
    {id:803,en:"art",tr:"sanat",level:"A1"},
    {id:804,en:"ball",tr:"top",level:"A1"},
    {id:805,en:"base",tr:"taban",level:"A1"},
    {id:806,en:"boat",tr:"tekne",level:"A1"},
    {id:807,en:"born",tr:"doğmuş",level:"A1"},
    {id:808,en:"bottom",tr:"alt",level:"A1"},
    {id:809,en:"bright",tr:"parlak",level:"A1"},
    {id:810,en:"calendar",tr:"takvim",level:"A1"},
    {id:811,en:"camera",tr:"kamera",level:"A1"},
    {id:812,en:"camp",tr:"kamp",level:"A1"},
    {id:813,en:"capital",tr:"başkent",level:"A1"},
    {id:814,en:"case",tr:"durum",level:"A1"},
    {id:815,en:"catch",tr:"yakalamak",level:"A1"},
    {id:816,en:"center",tr:"merkez",level:"A1"},
    {id:817,en:"century",tr:"yüzyıl",level:"A1"},
    {id:818,en:"certain",tr:"kesin",level:"A1"},
    {id:819,en:"chance",tr:"şans",level:"A1"},
    {id:820,en:"character",tr:"karakter",level:"A1"},
    {id:821,en:"cheap",tr:"ucuz",level:"A1"},
    {id:822,en:"choice",tr:"seçim",level:"A1"},
    {id:823,en:"church",tr:"kilise",level:"A1"},
    {id:824,en:"circle",tr:"daire",level:"A1"},
    {id:825,en:"clear",tr:"açık",level:"A1"},
    {id:826,en:"climb",tr:"tırmanmak",level:"A1"},
    {id:827,en:"clothes",tr:"kıyafetler",level:"A1"},
    {id:828,en:"club",tr:"kulüp",level:"A1"},
    {id:829,en:"coast",tr:"kıyı",level:"A1"},
    {id:830,en:"college",tr:"kolej",level:"A1"},
    {id:831,en:"common",tr:"yaygın",level:"A1"},
    {id:832,en:"company",tr:"şirket",level:"A1"},
    {id:833,en:"concert",tr:"konser",level:"A1"},
    {id:834,en:"corner",tr:"köşe",level:"A1"},
    {id:835,en:"couple",tr:"çift",level:"A1"},
    {id:836,en:"course",tr:"kurs",level:"A1"},
    {id:837,en:"dark",tr:"karanlık",level:"A1"},
    {id:838,en:"date",tr:"tarih",level:"A1"},
    {id:839,en:"dear",tr:"sevgili",level:"A1"},
    {id:840,en:"deep",tr:"derin",level:"A1"},
    {id:841,en:"degree",tr:"derece",level:"A1"},
    {id:842,en:"department",tr:"bölüm",level:"A1"},
    {id:843,en:"describe",tr:"tanımlamak",level:"A1"},
    {id:844,en:"design",tr:"tasarım",level:"A1"},
    {id:845,en:"detail",tr:"detay",level:"A1"},
    {id:846,en:"develop",tr:"geliştirmek",level:"A1"},
    {id:847,en:"difference",tr:"fark",level:"A1"},
    {id:848,en:"dinner",tr:"akşam yemeği",level:"A1"},
    {id:849,en:"direct",tr:"doğrudan",level:"A1"},
    {id:850,en:"direction",tr:"yön",level:"A1"},
    {id:851,en:"discover",tr:"keşfetmek",level:"A1"},
    {id:852,en:"discuss",tr:"tartışmak",level:"A1"},
    {id:853,en:"dish",tr:"tabak",level:"A1"},
    {id:854,en:"distance",tr:"mesafe",level:"A1"},
    {id:855,en:"double",tr:"çift",level:"A1"},
    {id:856,en:"dream",tr:"rüya",level:"A1"},
    {id:857,en:"drive",tr:"sürmek",level:"A1"},
    {id:858,en:"drop",tr:"damla",level:"A1"},
    {id:859,en:"dry",tr:"kuru",level:"A1"},
    {id:860,en:"during",tr:"sırasında",level:"A1"},
    {id:861,en:"early",tr:"erken",level:"A1"},
    {id:862,en:"earth",tr:"dünya",level:"A1"},
    {id:863,en:"east",tr:"doğu",level:"A1"},
    {id:864,en:"edge",tr:"kenar",level:"A1"},
    {id:865,en:"education",tr:"eğitim",level:"A1"},
    {id:866,en:"effect",tr:"etki",level:"A1"},
    {id:867,en:"else",tr:"başka",level:"A1"},
    {id:868,en:"end",tr:"son",level:"A1"},
    {id:869,en:"energy",tr:"enerji",level:"A1"},
    {id:870,en:"engine",tr:"motor",level:"A1"},
    {id:871,en:"enter",tr:"girmek",level:"A1"},
    {id:872,en:"environment",tr:"çevre",level:"A1"},
    {id:873,en:"equal",tr:"eşit",level:"A1"},
    {id:874,en:"especially",tr:"özellikle",level:"A1"},
    {id:875,en:"even",tr:"bile",level:"A1"},
    {id:876,en:"event",tr:"etkinlik",level:"A1"},
    {id:877,en:"ever",tr:"hiç",level:"A1"},
    {id:878,en:"example",tr:"örnek",level:"A1"},
    {id:879,en:"except",tr:"hariç",level:"A1"},
    {id:880,en:"excited",tr:"heyecanlı",level:"A1"},
    {id:881,en:"exercise",tr:"egzersiz",level:"A1"},
    {id:882,en:"exist",tr:"var olmak",level:"A1"},
    {id:883,en:"expect",tr:"beklemek",level:"A1"},
    {id:884,en:"expensive",tr:"pahalı",level:"A1"},
    {id:885,en:"experience",tr:"deneyim",level:"A1"},
    {id:886,en:"explain",tr:"açıklamak",level:"A1"},
    {id:887,en:"express",tr:"ifade etmek",level:"A1"},
    {id:888,en:"extra",tr:"ekstra",level:"A1"},
    {id:889,en:"factory",tr:"fabrika",level:"A1"},
    {id:890,en:"fail",tr:"başarısız olmak",level:"A1"},
    {id:891,en:"fair",tr:"adil",level:"A1"},
    {id:892,en:"fall",tr:"düşmek",level:"A1"},
    {id:893,en:"famous",tr:"ünlü",level:"A1"},
    {id:894,en:"farm",tr:"çiftlik",level:"A1"},
    {id:895,en:"fat",tr:"şişman",level:"A1"},
    {id:896,en:"fault",tr:"hata",level:"A1"},
    {id:897,en:"favourite",tr:"favori",level:"A1"},
    {id:898,en:"feel",tr:"hissetmek",level:"A1"},
    {id:899,en:"feeling",tr:"duygu",level:"A1"},
    {id:900,en:"festival",tr:"festival",level:"A1"}
];

// Kelimeleri birleştir
WORDS.push(...additionalA1);
